#' Examine batch effects
#'
#' Examine variation across batches on clustering and cluster proportion level, please refer to Mtrussart et al(CytofRUV)
#' for details.
#' @param prepsce a SingleCellExperiment object generated by batchPrep function
#' @param xdim integer, parameter for flowSOM clustering
#' @param ydim integer, parameter for flowSOM clustering
#' @param k integer, parameter for flowSOM clustering
#' @param seed numeric vector; the seed set for each run of clustering
#' @param downsample integer specifying the number of cells per sample for clustering
#' @param DR_method character string specifying the method for dimensionality reduction
#'
#' @return a ggplot object
#' @export
#'
#' @examples
#' #select TSNE for DR with default settings
#' batchExam(prepsce,method='TSNE')
#' #select UMAP for DR with 3000 cells per sample
#' batchExam(prepsce,k=30,downsample=3000,DR_method='TSNE')
#'
batchExam <- function(prepsce,xdim=10,ydim=10,k=20,seed=1234,downsample=2000,DR_method='UMAP'){
  set.seed(seed)
  if(!is(prepsce,'SingleCellExperiment')){
    message('Error: please input an sce object generated by batchPrep function.')
  }
  message('Running flowSOM clustering...')
  prepsce <- CATALYST::cluster(prepsce, features = type_markers(prepsce),
                               xdim = xdim, ydim = ydim, maxK = k, seed = seed)
  message('Running DR...')
  if(DR_method=='UMAP'){
    prepsce <- runDR(prepsce, dr = "UMAP", cells = downsample, features = "type")
    DR<-plotDR(prepsce, "UMAP", color_by = "batch")

  } else if(DR_method=='TSNE'){
    prepsce <- runDR(prepsce, dr = "TSNE", cells = downsample, features = "type")
    DR<-plotDR(prepsce, "TSNE", color_by = "batch")

  } else{
    message('Please choose the right method for dimension reduction: UMAP or TSNE')
  }
  message('Plotting...')
  Stack<-plotAbundances(prepsce, k = paste0('meta',k), by = "sample_id")
  plot_grid(DR, Stack,
            labels = c('A','B'),
            nrow = 1, align = "l", label_size = 10)
}
