#' Plot total cell population frequencies after binary classification
#'
#'Visualisation of cell population frequencies/composition after binary classification, in the format of bar plot
#' @param sce a SingleCellExperiment object
#' @param binary_results list, results of binary classification
#' @param style character string indicating the type of the plot, options are 'bar' or 'pie', default is 'bar'
#' @return a ggplot object
#' @export
#'
#' @examples
#' plotbcFreq(sce,binary.results,style='pie')
#'
plotbcFreq<-function(sce,binary.results,style='bar'){

  #define the function of binary_summary
#' Title
#'
#' @param data sce object
#' @param binary.results vector generated by running binaryClass
#'
#' @return a data frame
#' @export
#'
  binary_summary<-function (data = NULL, binary.results = NULL)
  {
    if (is.null(data)) {
      return("Please provide data. Use load_data")
    }
    if (is.null(binary.results)) {
      return("Please provide binary classification results. Use binary_class")
    }
    frequencies <- data.frame(table(binary.results[, "Cell.Type"]))
    colnames(frequencies) <- c("Cell.Type", "Frequency")
    frequencies[, "Percentage"] <- frequencies[, "Frequency"] *
      100/sum(frequencies[, "Frequency"])
    medians <- data.frame(matrix(nrow = dim(frequencies)[1],
                                 ncol = dim(data)[2]))
    rownames(medians) <- frequencies[, 1]
    colnames(medians) <- colnames(data)
    for (i in frequencies[, 1]) {
      medians[i, ] <- as.vector(apply(data[binary.results[,
                                                          "Cell.Type"] == i, ], 2, median))
    }
    medians[, "Cell.Type"] <- rownames(medians)
    to.return <- merge(medians, frequencies, by = "Cell.Type")
    return(to.return)
  }
  exprs_n <- t(assay(sce, 'exprs'))
  binary.summary <- binary_summary(exprs_n, binary.results)

  if(style=='bar'){
    p<-ggplot(binary.summary,  aes("", Percentage, fill = Cell.Type)) +
      geom_bar(stat="identity", position = position_dodge())  +
      theme_minimal()+
      scale_y_continuous()+
      geom_text(aes(label=round(Percentage,2)), position=position_dodge(width=0.9), vjust=0.1,size=3.5)+
      labs(title = "Cell Abundance", x = "Cell types", y = "Percentage(%)")+
      coord_flip() } else if(style=='pie'){

    p<-ggplot(binary.summary, aes(x = "", y = Percentage, fill = Cell.Type)) +
      geom_bar(stat = "identity", width = 1, color = "white") +
      coord_polar("y") +
      labs(fill = "Cell types") +
      scale_fill_discrete(labels = paste(binary.summary$Cell.Type, '(',round(binary.summary$Percentage,1),'%',')'))+
      theme_void()
      } else{
        stop('Please choose the right plot type: bar or pie')
      }
  return(p)
}


