#' Run Phenograph algorithm for clustering
#'
#' @param sce a SingleCellExperiment object
#' @param k integer; number of nearest neighbors
#' @param downsample logical/numeric vector; default is F which means the input data will not be downsampled;
#' Or input can be a number to specify how many cells per sample to be clustered;
#' @param seed numeric vector; the seed set for each run of clustering
#' @param type_markers logical vector; default is NULL, which means only type markers will be used for clustering;if it is F,
#' then all markers will be used for clustering
#'
#' @return a SingleCellExpreriment with newly added data of Phenograph clustering results as below:
#'
#' -colData: cluster_id of each cell inferred by Phenograph
#'
#' -metadata:cluster_codes/rph, stores the clustering levels generated by Phenograph
#' @export
#' @examples
#' Use type markers to run Phenograph clustering for sce object with 1000 cells per sample,k set as 10
#' sce_rph<-runPheno(sce,k=10,downsample = 1000,seed = 1234, type_markers=T)
#' Use all markers and all cells for clustering, k set as 20
#' sce_rph<-runPheno(sce,k=20,downsample = NULL,seed=1234,type_markers=F)
runPheno<-function(sce,k,downsample=NULL,seed=1234,type_markers=T){
  #set the seed
  set.seed(seed)
  if(is.null(sce)){
    message('sce argument is missing, with no default, please input an sce object')
  }
  if(!is(sce,'SingleCellExperiment')){
    stop('Error:Input data has to be a sce object')
  }
  #see if downsampling is needed
  if(is.null(downsample)){
    message('All cells are being used for clustering...')
    Sys.sleep(2)
    #the number of downsample must be a positive number
  } else if(is.numeric(downsample)==T & downsample>0){
    message('Perform downsampling ',downsample, ' cells per sample')
    #take the same number of cells from each patient sample
    inds <- split(1:length(colData(sce)[,'sample_id']), colData(sce)[,'sample_id'])
    down_cells <- pmin(table(colData(sce)[,'sample_id']), downsample)
    #set the seed for downsampling
    set.seed(seed)
    down_inds <- lapply(names(inds), function(i){
      s <- sample(inds[[i]], down_cells[i], replace = FALSE)
    })
    down_inds <- unlist(down_inds)
    sce<-sce[,down_inds]
  }else{
    stop('Error: downsample has to be a positive interger!')
  }
  #extract expression data from sce object
  data <- t(assay(sce,'exprs'))
  #determine whether to only use type markers or all markers for clustering
  if(type_markers==T){
    data <- data[,type_markers(sce)]
    message('Only use type markers for phenograph clustering...')
    Sys.sleep(2)
  }else{
  message('Use all markers for phenograph clustering...')
  Sys.sleep(2)
  }
  #Phenograph clustering
  rph_output <- Rphenograph(data, k = k)
  identity <- factor(membership(rph_output[[2]]))
  r_sce <- sce
  r_sce$cluster_id <- unlist(identity)
  metadata(r_sce)$cluster_codes <- data.frame(
    rph = factor(levels(identity), levels = levels(identity)))
  return(r_sce)
}
